export const SET_JOURNALS = 'SET_JOURNALS';
export const SET_ACTIVE_JOURNAL = 'SET_ACTIVE_JOURNAL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_LOADING = "SET_LOADING";
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED= 'USER_LOADED';
export const AUTH_ERR = 'AUTH_ERR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_FAIL = 'EMAIL_FAIL';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const ERROR_ALERTS = 'ERROR_ALERTS';
export const CLEAR_STATUS = 'CLEAR_STATUS'